sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - mkdir travis-bin
  - wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
#  - ls -l $PWD/travis-bin
#  - chromedriver --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success: bash <(curl -s https://codecov.io/bash)